# Code below is autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef double _log_factorial(int x) nogil
cdef int _poisson_small(double mean) nogil
cdef int _poisson_large(double mean) nogil
cdef int _poisson_value(double mean) nogil
cdef double _normal_value() nogil
