# Code below is autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef bint _get_particle_candidate(float[:, :] _image_pdf, int particle_index, float[:] xp, float[:] yp, float min_distance) nogil
cdef double _get_closest_distance(float x, float y, float[:] xp, float[:] yp) nogil
