version: 1.0.{build}

image:
  - macOS
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON_VERSION: 3.8
      OS_LABEL: win
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON_VERSION: 3.8
      OS_LABEL: linux
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      PYTHON_VERSION: 3.8
      OS_LABEL: macos

install:
  - PS: if ($env:OS_LABEL -eq 'win') { choco install python --version $env:PYTHON_VERSION }
  - PS: if ($env:OS_LABEL -eq 'linux') { sudo apt-get update && sudo apt-get install -qqy python$env:PYTHON_VERSION }
  - PS: if ($env:OS_LABEL -eq 'macos') { brew install python$env:PYTHON_VERSION }
  - PS: python$env:PYTHON_VERSION -m pip install --upgrade pip
  - PS: python$env:PYTHON_VERSION -m pip install cibuildwheel

build_script:
  - PS: cibuildwheel --output-dir wheelhouse

test_script:
  - PS: pytest

artifacts:
  - path: wheelhouse
    name: wheelhouse
