version: 1.0.{build}

image:
  - macOS
  - Visual Studio 2019
  - Ubuntu

environment:
  matrix:
    - PYTHON_VERSION: 3.8
    - PYTHON_VERSION: 3.9

build_script:
  - cmd: cibuildwheel --output-dir wheelhouse

test_script:
  - cmd: pytest

artifacts:
  - path: wheelhouse
    name: wheelhouse
