version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      OS_LABEL: win
      PYTHON_VERSION: 3.8
      PYTHON: C:\\Python38
      PYTHON_CMD: C:\\Python38\\python.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      OS_LABEL: linux
      PYTHON_VERSION: 3.8
      PYTHON: $HOME/venv3.8/bin
      PYTHON_CMD: $HOME/venv3.8/bin/python
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
      OS_LABEL: macos
      PYTHON_VERSION: 3.8
      PYTHON: /usr/local/bin
      PYTHON_CMD: /usr/local/bin/python3.8

init:
  - PS: Set-Alias _python $env:PYTHON_CMD
  - PS: _python -m pip install --upgrade pip
  - PS: _python -m pip install virtualenv
  - PS: _python -m virtualenv $HOME/venv$env:PYTHON_VERSION
  - PS: _python -m pip install --upgrade pip
  - PS: _python -m pip install cibuildwheel

install:
  # - PS: if ($env:OS_LABEL -eq 'win') { choco install python --version $env:PYTHON_VERSION }
  # - PS: if ($env:OS_LABEL -eq 'linux') { sudo apt-get update && sudo apt-get install -qqy python$env:PYTHON_VERSION }
  # - PS: if ($env:OS_LABEL -eq 'macos') { brew install python@$env:PYTHON_VERSION }
  - PS: _python -m pip install cibuildwheel

build_script:
  - cmd: python -m cibuildwheel --output-dir wheelhouse"

test_script:
  - cmd: python -m pytest

artifacts:
  - path: wheelhouse
    name: wheelhouse
