version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON_VERSION: 3.8
      OS_LABEL: win
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYTHON_VERSION: 3.8
      OS_LABEL: linux
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
      PYTHON_VERSION: 3.8
      OS_LABEL: macos

install:
  # - PS: if ($env:OS_LABEL -eq 'win') { choco install python --version $env:PYTHON_VERSION }
  # - PS: if ($env:OS_LABEL -eq 'linux') { sudo apt-get update && sudo apt-get install -qqy python$env:PYTHON_VERSION }
  # - PS: if ($env:OS_LABEL -eq 'macos') { brew install python@$env:PYTHON_VERSION }
  # - PS: python3 -m pip install --upgrade pip
  - PS: pip install pipx
  - PS: pipx --python python$env:PYTHON_VERSION install cibuildwheel

build_script:
  - PS: pipx run cibuildwheel --output-dir wheelhouse

test_script:
  - PS: pipx run pytest

artifacts:
  - path: wheelhouse
    name: wheelhouse
