# REF: https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

version: "{build}"

shallow_clone: false

# branches to build
branches:
  # whitelist
  only:
    - main

only_commits:
  files:
    # only trigger build if these files change
    #https://www.appveyor.com/docs/how-to/filtering-commits/#skip-commits-2
    - src/
    - pyproject.toml
    - .appveyor.yml

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      OS_NAME: linux
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      OS_NAME: win
    - APPVEYOR_BUILD_WORKER_IMAGE: macos-monterey
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
      OS_NAME: darwin

  access_token:
    secure: VDbNqf7th0x0/u2BDKnebeGa6ljTeME+9WKs2hnZPiBbIttfvHuaBsku/tL/JURS

stack: python 3.8

cache:
  - cache-pip
  - cache-cibuildwheel
  - .nox

init:
  - cmd: set PATH=C:\Python38;C:\Python38\Scripts;%PATH%

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps:
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
      throw "There are newer queued builds for this pull request, failing early." }
  - python -m pip install --upgrade pip --cache-dir cache-pip
  - python -m pip install pipx --cache-dir cache-pip

build_script:
  # build wheels for windows, also sdist
  - cmd: pipx run nox --sessions build_wheel build_sdist
  # build wheels for darwin
  - sh: "[[ $OS_NAME == 'darwin' ]] && brew install python@3.8 python@3.9 python@3.10 python@3.11 llvm libomp || true"
  - sh: "[[ $OS_NAME == 'darwin' ]] && NPX_CYTHON_THREADS=2 pipx run nox --sessions build_wheel || true"
  # build wheels for linux
  - sh: "[[ $OS_NAME == 'linux' ]] && CIBW_CACHE_PATH='cache-cibuildwheel' pipx run cibuildwheel --output-dir wheelhouse || true"

test_script:
  - sh: "[[ $OS_NAME == 'linux' ]] && sudo apt update || true"
  - sh: "[[ $OS_NAME == 'linux' ]] && sudo apt install -y python3.11-full python3.10-full python3.10-venv libpython3.10-dev libpython3.11-dev || true"
  - pipx run nox --sessions tests_on_wheels

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
  - path: "wheelhouse\\*.tar.gz"
    name: SDist

# build_script:
#   - ps: $env:CIBW_CACHE_PATH = "cache-cibuildwheel"
#   - pipx run cibuildwheel --output-dir wheelhouse
#   - sh: "[[ $OS_NAME == 'linux' ]] && pipx run build --sdist --outdir wheelhouse || true"
# test_script:
#   - pipx run twine check wheelhouse/*.whl
#   - pipx run tox

notifications:
  - provider: Email
    to:
      - "{{commitAuthorEmail}}"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
  - provider: GitHubPullRequest
    auth_token:
      secure: VDbNqf7th0x0/u2BDKnebeGa6ljTeME+9WKs2hnZPiBbIttfvHuaBsku/tL/JURS
    template: "{{#passed}}:white_check_mark:{{/passed}}{{#failed}}:x:{{/failed}} [Build {{&projectName}} {{buildVersion}} {{status}}]({{buildUrl}}) (commit {{commitUrl}} by @{{&commitAuthorUsername}})"

deploy:
  # skip_tags: true
  on:
    branch: main # release from main branch only
    APPVEYOR_REPO_TAG: true # deploy on tag push only
  provider: GitHub
  # tag: $(APPVEYOR_REPO_TAG_NAME)
  repository: "HenriquesLab/NanoPyx"
  release: Latest
  description: "Latest build of NanoPyx"
  auth_token:
    secure: VDbNqf7th0x0/u2BDKnebeGa6ljTeME+9WKs2hnZPiBbIttfvHuaBsku/tL/JURS
  artifact: Wheels, SDist
  draft: true
  prerelease: false
