[build-system]
requires = ["setuptools>=42", "wheel", "numpy>=1.19.0", "cython>=0.29.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nanopyx"
version = "0.0.1"
dynamic = ["readme", "urls", "classifiers", "authors", "requires-python", "description"]