[build-system]
requires = ["setuptools>=42", "wheel>=0.38.4", "cython>=0.29.0", "numpy>=1.19.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nanopyx"
version = "0.0.1"
dynamic = ["urls", "classifiers", "authors", "requires-python", "description", "readme"]