# Code below is autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef float[:] _get_max(float[:] arr, int x1, int x2) nogil
cdef float[:] _get_min(float[:] arr, int x1, int x2) nogil
