# Code below is autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef float[:, :] _assemble_frame_from_blocks(float[:, :, :] blocks_stack, int n_rows, int n_cols) nogil
cdef float[:, :, :] _split_frame_into_blocks(float[:, :] img, int n_rows, int n_cols) nogil
