cdef extern from "_c_catmull_rom.h":
    double _c_cubic(double v) nogil

from .interpolation_nearest_neighbor cimport Interpolator as InterpolatorNearestNeighbor

# pyx2pxd: starting point
# Code below is autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef double _interpolate(float[:,:] image, double x, double y) nogil

cdef class Interpolator(InterpolatorNearestNeighbor):
    cdef float _interpolate(self, float x, float y) nogil
