cdef extern from "_c_interpolation_bilinear.h":
    float _c_interpolate(float * image, float r, float c, int rows, int cols) nogil

from .interpolation_nearest_neighbor cimport Interpolator as InterpolatorNearestNeighbor

# pyx2pxd: starting point
# Code below is autogenerated by pyx2pxd

cdef float _interpolate(float[:,:] image, float x, float y) nogil

cdef class Interpolator(InterpolatorNearestNeighbor):
    cdef float _interpolate(self, float x, float y) nogil
