# autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef void _simple_state_transition_model(int[:] states, double p_on, double p_transient_off, double p_permanent_off, int initial_state) nogil
