# autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd

cdef float _interpolate_y(int x1, int y1, int x2, int y2, int x)
cdef _compute(float[:, :] images, float[:] data_a1, float[:] data_b1, float[:] data_a2, float[:] data_b2)
cdef float[:] _get_interpolated_values(float y, float x, float[:, :] images, int maxx)
cdef float _get_sine(float angle, float cos_a) nogil
