# autogenerated by pyx2pxd - https://github.com/HenriquesLab/pyx2pxd


cdef float _calculate_ppmcc(float[:, :] im1, float[:, :] im2, int shift_x, int shift_y) nogil
cdef float _pearson_correlation(float[:,:] im1, float[:,:] im2) nogil
