name: Build and Test Apple Silicon wheels

on: workflow_dispatch

jobs:
    build_wheels:
        runs-on: [self-hosted, macOS, ARM64]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
        
            - name: Setup Python
              uses: actions/setup-python@v4
        
            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.15.0
        
            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse
              # to supply options, put them in 'env', like:
              env:
                CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}
                CIBW_ARCHS: arm64
                CIBW_BUILD_VERBOSITY: 1
                CIBW_TEST_COMMAND: "pytest {project}/tests"

            - name: Test wheels
              run: python -m nox --sessions test_wheel
                
            - uses: actions/upload-artifact@v3
              with:
                path: ./wheelhouse/*.whl