name: (self-hosted) Build and Publish Wheels

on: workflow_dispatch

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macOS-ARM
            runner: [self-hosted, macOS, ARM64]
            archs: arm64
            cibw_build: cp39-macosx_arm64 cp310-macosx_arm64 cp311-macosx_arm64 cp312-macosx_arm64
          - os: manylinux
            runner: [self-hosted, Ubuntu, Native]
            archs: auto
            cibw_build: cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64
          - os: windows
            runner: [self-hosted, Windows]
            archs: auto
            cibw_build: cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
            3.12 

      - name: Install cibuildwheel and nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==73.0.1
          python -m pip install cibuildwheel
          python -m pip install nox

      - name: Build sdist (only on Windows)
        if: matrix.os == 'windows'
        run: python -m nox --sessions build_sdist

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_ARCHS: ${{ matrix.archs }}
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y epel-release &&
            yum install -y ocl-icd-devel opencl-headers
          CIBW_ENVIRONMENT_LINUX: >
            PIP_ONLY_BINARY=pillow
            PIP_NO_BUILD_ISOLATION=1
            CFLAGS="-I/usr/include"
            LDFLAGS="-L/usr/lib64"
            CL_INC_DIR=/usr/include
            CL_LIB_DIR=/usr/lib64
            CL_LIBNAME=OpenCL
          CIBW_ENVIRONMENT: >
            PIP_ONLY_BINARY=pillow
            PIP_NO_BUILD_ISOLATION=1
          CIBW_ENVIRONMENT_PASS_LINUX: CL_INC_DIR,CL_LIB_DIR,CL_LIBNAME,CFLAGS,LDFLAGS

      - name: Test wheels (only on macOS ARM64)
        if: matrix.os == 'macOS-ARM'
        run: python -m nox --sessions test_wheel

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Combine all wheels and sdists
        run: |
          mkdir -p final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;
          find dist -name "*.tar.gz" -exec cp {} final_dist/ \;

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.BMS_DEPLOY_PYPI_TOKEN }}
          packages-dir: ./final_dist/