name: Build and Test Manylinux wheel

on: workflow_dispatch

jobs:
  build_linux_39_and_above_wheels:
    name: Build python ${{ matrix.cibw_python }} ${{ matrix.cibw_arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ubuntu-latest]
        cibw_python: ["cp39-*", "cp310-*", "cp311-*"]
        cibw_manylinux: [manylinux2014]
        cibw_arch: ["x86_64"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.9"
      - name: Install cibuildwheel
        run:
          python -m pip install --upgrade pip
          python -m pip install pipx
          python -m pip install cibuildwheel
      - name: Build the wheel
        run:
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_arch }}
          CIBW_SKIP: "*-musllinux_*"
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.cibw_manylinux }}
          CIBW_MANYLINUX_I686_IMAGE: ${{ matrix.cibw_manylinux }}
          CIBW_BUILD_VERBOSITY: 1
          CIBW_TEST_COMMAND: "pytest {project}/tests"
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.whl