name: Build Docs Website - Test if it works

# build the documentation whenever there are new commits on main
on:
  # creates a button and only builds upon press
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: [py310]
    steps:
      - uses: actions/checkout@v3

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: pip install -e .[doc]
      # ADJUST THIS: build your documentation into docs/.
      # We use a custom build script for pdoc itself, ideally you just run `pdoc -o docs/ ...` here.
      - run: |
          mkdir -p docs
          VERSION=$(python -c "import runBuildTools; print(runBuildTools.get_version())")
          pdoc src/nanopyx -o docs/$VERSION

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: [py310]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
