name: Build and Test wheels

on: workflow_dispatch

jobs:
  build_sdist:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox
          python -m nox --sessions build_sdist
      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: ./wheelhouse/*.tar.gz

  build_wheels:
    name: Build wheels on Python ${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}
    needs: build_sdist
    strategy:
      matrix:
          include:
          - os: windows-latest
            python: 39
            platform_id: win_amd64
          - os: windows-latest
            python: 310
            platform_id: win_amd64
          - os: windows-latest
            python: 311
            platform_id: win_amd64

          # - os: ubuntu-latest
          #   python: 39
          #   platform_id: manylinux_x86_64
          #   manylinux_image: manylinux2014
          # - os: ubuntu-latest
          #   python: 310
          #   platform_id: manylinux_x86_64
          #   manylinux_image: manylinux2014
          # - os: ubuntu-latest
          #   python: 311
          #   platform_id: manylinux_x86_64
          #   manylinux_image: manylinux2014

          - os: macos-latest
            python: 39
            platform_id: macosx_x86_64
          - os: macos-latest
            python: 310
            platform_id: macosx_x86_64
          - os: macos-latest
            python: 311
            platform_id: macosx_x86_64

          - os: macos-latest
            python: 39
            platform_id: macosx_arm64
          - os: macos-latest
            python: 310
            platform_id: macosx_arm64
          - os: macos-latest
            python: 311
            platform_id: macosx_arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  

      - name: Run Nox Quick-Tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox
          python -m nox --sessions clear_wheelhouse build_wheel build_sdist test_wheel
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl