name: Build Docker Image

on:
  schedule:
    - cron: '0 2 * * 0' # run at 2 AM UTC on Sundays

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:        

    -
      name: Checkout
      uses: actions/checkout@v3

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PUSH }}
        
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: henriqueslab/nanopyx:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      # see also https://docs.docker.com/build/ci/github-actions/examples/
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
