name: Build and Test Mac x86 wheels

on: workflow_dispatch

jobs:

  build_wheels:
    name: Build wheels on Python ${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          python: 39
          platform_id: macosx_x86_64
        - os: macos-latest
          python: 310
          platform_id: macosx_x86_64
        - os: macos-latest
          python: 311
          platform_id: macosx_x86_64

    steps:
        - uses: actions/checkout@v4
    
        # Used to host cibuildwheel
        - uses: actions/setup-python@v5
    
        - name: Install cibuildwheel
          run: python -m pip install cibuildwheel==2.16.2
    
        - name: Build wheels
          run: python -m cibuildwheel --output-dir wheelhouse
          env:
            CIBW_BUILD: cp39-macosx_x86_64 cp310-macosx_x86_64 cp311-macosx_x86_64
            # to supply options, put them in 'env', like:
            # env:
            #   CIBW_SOME_OPTION: value
    
        - uses: actions/upload-artifact@v4
          with:
            name: wheel-manylinux
            path: ./wheelhouse/*.whl