name: Deploy Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  # Download wheels and sdist and depply them to pypi
  deploy:
    runs-on: [py310, linux]
    steps:
      - name: Download wheels
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "*.whl"
          out-file-path: "dist/"

      - name: Download sdist
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          tarBall: true

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.BMS_DEPLOY_TESTPYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: "dist/"

      # - name: Publish package to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     password: ${{ secrets.BMS_DEPLOY_PYPI_TOKEN }}
      #     packages_dir: dist/