name: deploy package

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  # Download wheels and sdist and depply them to pypi
  deploy:
    runs-on: [py310, linux]
    steps:
      - name: Download wheels
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          fileName: "*.whl"
          out-file-path: "dist/"

      - name: Download sdist
        uses: robinraju/release-downloader@v1.7
        with:
          latest: true
          tarBall: true

      - run: ls dist/

      - name: Publish package to TestPyPI
        run: |
          python -m pip install twine
          python -m twine upload --repository testpypi -u "__token__" -p ${{ secrets.BMS_DEPLOY_TESTPYPI_TOKEN }} dist/*

      # - name: Publish package to PyPI
      #   run: |
      #     python -m twine -u "__token__" -p ${{ secrets.BMS_DEPLOY_PYPI_TOKEN }} dist/*