name: generate gource movie

on:
  # creates a button
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  generate_movie:
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Install packages
      #   run: |
      #     apt-get update
      #     apt-get install -y --no-install-recommends \
      #       ffmpeg \
      #       gource \
      #       xvfb
      #     pip install -U pipx

      - name: Generate movie
        run: |
          mkdir ./faces
          wget -o ./faces/HannahSHeil.jpg https://henriqueslab.github.io/images/HH.jpg
          wget -o ./faces/Bruno\ Saraiva.jpg https://henriqueslab.github.io/images/researchers_BS.jpg
          wget -o ./faces/Inês\ Cunha.jpg https://henriqueslab.github.io/images/IC.jpg
          wget -o ./faces/António\ Brito.jpg https://henriqueslab.github.io/images/researchers_AB.jpg
          pipx run gitfaces ./ ./faces
          xvfb-run gource --output-custom-log repo-activity.log
          python3 -c "txt=open('repo-activity.log').read();txt=txt.replace('Bruno Manuel Santos Saraiva', 'Bruno Saraiva').replace('inesmcunha', 'Inês Cunha').replace('antmsbrito', 'António Brito');open('repo-activity.log', 'w').write(txt)"
          xvfb-run gource -a 1 -s 1 -c 2 --user-image-dir ./faces repo-activity.log -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -pix_fmt yuv420p gource.mp4

      - name: Archive generated movie
        uses: actions/upload-artifact@v3
        with:
          name: gource-movie
          path: gource.mp4
