name: "Pull Request Labeler"
on:
  - pull_request_target

permissions: {}

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write  
    steps:
    - name: Label the PR
      uses: gerrymanoim/pr-prefix-labeler@c8062327f6de59a9ae1c19f7f07cacd0b976b6fa 
      continue-on-error: true