name: test-oncall
# does a quick test

on:
  push:
    branches: ["main"]
    paths:
      # only run if src or tests changes
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - "src/**"
      - "tests/**"
      - "setup.py"
      - "noxfile.py"
      - "pyproject.toml"
  pull_request:
    branches: ["main"]

  # creates a button
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  oncall_mechanic_ubuntu:
    runs-on: [self-hosted, linux]
    steps:
      - name: Setup Ubuntu dependencies
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
          apt install -y curl systemctl build-essential lsb-release python3-pip git libgl1-mesa-glx libglib2.0-0 ca-certificates jq htop gource ffmpeg xvfb python3.10-venv libavcodec-extra python3.11-full python3.10-full libpython3.10-dev libpython3.11-dev
          python3 -m pip install --upgrade pipx
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run Nox Quick-Tests
        run: |
          pipx run nox --sessions test_source-3.10
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml # optional
          flags: pytests # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
  oncall_mechanic_macosx:
    runs-on: [self-hosted, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Nox Quick-Tests
        run: |
          pip3 install pipx
          python3 -m pipx run nox --sessions test_source-3.10
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}
