name: nanopyx on-call mechanic
# does a quick test

on:
  push:
    branches: ["main"]
    paths:
      # only run if src or tests changes
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - "src/**"
      - "tests/**"
      - "setup.py"
  pull_request:
    branches: ["main"]

  # creates a button
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  oncall_mechanic:
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nox
        uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.10"
      - name: Run Nox
        run: |
          python -m pip install pipx
          pipx run nox --sessions tests_on_source-3.10
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}
