name: Test - Oncall
# does a quick test

on:
  push:
    branches: ["main"]
    paths:
      # only run if src or tests changes
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - "src/**"
      - "tests/**"
      - "setup.py"
      - "noxfile.py"
      - "pyproject.toml"
  pull_request:
    branches: ["main"]

  # creates a button
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  test_on_ubuntu_container:
    runs-on: [self-hosted, Ubuntu]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.9
            3.10
            3.11
      - name: Run Nox Quick-Tests
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade nox
          python -m nox --sessions test_source
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel }}
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml # optional
          flags: pytests # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }}
