name: Ubuntu Wheel Maker

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build pipx
          pip install -e ".[test]"

      - name: Build wheels and stdist
        run: |
          nox --session build_wheel-${{ matrix.python-version }} test_wheel-${{ matrix.python-version }}
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/